'use client';
import { useEffect, useState } from 'react';
import { Building2, Plus, X } from 'lucide-react';
import { shortLetOperatorsApi } from '@/lib/api';
import { ShortLetOperator, ShortLetOperatorStatus } from '@/types';
import { useToast } from '@/components/ui/Toast';

const empty = { name: '', contactPerson: '', phone: '', email: '', websiteUrl: '', status: ShortLetOperatorStatus.PENDING };
export default function AdminShortLetOperatorsPage() {
  const [items,setItems]=useState<ShortLetOperator[]>([]); const [filter,setFilter]=useState(''); const [form,setForm]=useState<(Partial<ShortLetOperator> & {name:string;phone:string})|null>(null); const [saving,setSaving]=useState(false); const {success,error}=useToast();
  const load=()=>shortLetOperatorsApi.adminList(filter).then(r=>setItems(r.data)).catch(e=>error(e.message));
  useEffect(()=>{ void load(); },[filter]);
  const save=async()=>{if(!form)return;setSaving(true);try{form.id?await shortLetOperatorsApi.update(form.id,form):await shortLetOperatorsApi.create(form);success('Operator saved');setForm(null);load();}catch(e:any){error(e.message)}finally{setSaving(false)}};
  const status=async(id:string,value:string)=>{try{await shortLetOperatorsApi.setStatus(id,value);load();}catch(e:any){error(e.message)}};
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-navy-900">Short Let Operators</h1><p className="text-sm text-veriq-muted">Approve operators and manage the master directory.</p></div><button className="btn-primary flex items-center gap-2" onClick={()=>setForm(empty)}><Plus className="h-4 w-4"/>Add operator</button></div><div className="flex gap-3"><select className="input max-w-xs" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{Object.values(ShortLetOperatorStatus).map(v=><option key={v} value={v}>{v}</option>)}</select></div><div className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="grid grid-cols-[2fr_1.2fr_1fr_1fr_auto] gap-4 border-b bg-slate-50 px-5 py-3 text-xs font-semibold text-slate-500"><span>Operator</span><span>Contact</span><span>Approval</span><span>Portal</span><span>Action</span></div>{items.length===0?<p className="p-8 text-center text-sm text-slate-500">No operators found.</p>:items.map(item=><div key={item.id} className="grid grid-cols-[2fr_1.2fr_1fr_1fr_auto] items-center gap-4 border-b px-5 py-4 text-sm last:border-0"><div><p className="font-semibold text-navy-900">{item.name}</p><p className="text-xs text-slate-500">{item.websiteUrl||'No website'}</p></div><div><p>{item.contactPerson||'Not provided'}</p><p className="text-xs text-slate-500">{item.phone}</p></div><select className="input !py-2" value={item.status} onChange={e=>status(item.id,e.target.value)}>{Object.values(ShortLetOperatorStatus).map(v=><option key={v} value={v}>{v}</option>)}</select><span className="capitalize">{item.portalStatus.replace('_',' ')}</span><button className="btn-outline !px-3 !py-2" onClick={()=>setForm({...empty,...item,id:item.id})}>Edit</button></div>)}</div>{form&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-lg bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-lg font-bold">{form.id?'Edit':'Add'} operator</h2><button onClick={()=>setForm(null)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{[['name','Operator name *'],['contactPerson','Contact person'],['phone','Phone number *'],['email','Email address'],['websiteUrl','Website / booking URL']].map(([key,label])=><label key={key} className={key==='websiteUrl'?'sm:col-span-2':''}><span className="label">{label}</span><input className="input" type={key==='email'?'email':key==='websiteUrl'?'url':'text'} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><button disabled={saving||!form.name||!form.phone} onClick={save} className="btn-primary mt-6 w-full">{saving?'Saving...':'Save operator'}</button></div></div>}</div>;
}
