import { PropertyType } from '@/types';

export type ListingField = { key: string; label: string; options?: string[]; type?: 'number' | 'text'; required?: boolean };
const o = (key: string, label: string, options: string[], required = true): ListingField => ({ key, label, options, required });
const n = (key: string, label: string, required = true): ListingField => ({ key, label, type: 'number', required });
const common = {
  meter: ['Private Prepaid', 'Private Postpaid', 'Shared Meter', 'Included in Service Charge', 'Not Confirmed'],
  parking: ['Dedicated', 'Shared Compound', 'Limited', 'Street Only', 'None', 'Not Confirmed'],
  storage: ['Private Tank', 'Shared Tank', 'No Dedicated Storage', 'Not Confirmed'],
  ventilation: ['Well', 'Moderate', 'Poor', 'Not Personally Verified'],
  lighting: ['Good', 'Moderate', 'Limited', 'Not Personally Verified'],
};
const base = (extra: ListingField[]): ListingField[] => extra;

export const LISTING_FIELDS: Record<string, ListingField[]> = {
  [PropertyType.FLAT]: base([
    o('bathroomArrangement','Bathroom Arrangement',['All Private','Some Shared','Outside Apartment','Not Confirmed']), o('kitchenType','Kitchen Type',['Private Kitchen','Kitchenette','Shared Kitchen','No Kitchen','Not Confirmed']), o('ensuiteArrangement','Ensuite Arrangement',['All Bedrooms','Some Bedrooms','None','Not Applicable','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingAvailability','Parking Availability',common.parking), o('waterStorage','Water Storage',common.storage), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Private Entrance/Facilities','Shared Entrance Only','Some Shared Facilities','Limited','Not Confirmed']), o('buildingOccupancy','Building Occupancy',['Few Units','Moderate','Dense','Newly Completed/Unoccupied','Not Confirmed'],false),
  ]),
  [PropertyType.MINI_FLAT]: base([
    o('bathroomArrangement','Bathroom Arrangement',['Private Inside Unit','Private Outside Unit','Shared','Not Confirmed']), o('kitchenArrangement','Kitchen Arrangement',['Private Kitchen','Kitchenette','Shared','No Kitchen','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingAvailability','Parking Availability',common.parking), o('waterStorage','Water Storage',common.storage), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Private Entrance/Facilities','Shared Entrance','Limited','Not Confirmed']),
  ]),
  [PropertyType.SELF_CONTAIN]: base([
    o('kitchenArrangement','Kitchen Arrangement',['Private Kitchen','Kitchenette','Kitchen Space / Corner','No Dedicated Kitchen']), o('bathroomLocation','Bathroom Location',['En-suite / Inside Room','Private but Outside Room']), o('electricityMetering','Electricity Metering',['Prepaid Meter','Postpaid Meter','Shared Meter','Electricity Included in Rent','No Dedicated Meter']), o('parkingAvailability','Parking Availability',['Available','Limited','Not Available']), o('waterStorage','Water Storage / Backup',['Overhead Tank','Ground Tank','Both','No Dedicated Storage','Not Sure']), o('roomSize','Room Size',['Small','Medium','Large','Very Large']), o('ventilation','Ventilation',['Excellent','Good','Fair','Poor']), o('naturalLighting','Natural Lighting',['Excellent','Good','Fair','Poor']), o('privacyLevel','Privacy Level',['High','Moderate','Low']), o('wardrobeStorage','Wardrobe / Storage',['Built-in Wardrobe','Freestanding Wardrobe','Storage Space Only','None'],false),
  ]),
  [PropertyType.ROOM_AND_PARLOUR]: base([
    o('bathroomArrangement','Bathroom / Toilet Arrangement',['En-suite / Inside Unit','Private but Outside Unit']), o('kitchenArrangement','Kitchen Arrangement',['Private Kitchen','Kitchenette','Kitchen Space / Corner','No Dedicated Kitchen']), o('electricityMetering','Electricity Metering',['Prepaid Meter','Postpaid Meter','Shared Meter','Electricity Included in Rent','No Dedicated Meter']), o('parkingAvailability','Parking Availability',['Available','Limited','Not Available']), o('waterStorage','Water Storage / Backup',['Overhead Tank','Ground Tank','Both','No Dedicated Storage','Not Sure']), o('roomSize','Room Size',['Small','Medium','Large','Very Large']), o('parlourSize','Parlour Size',['Small','Medium','Large','Very Large']), o('ventilation','Ventilation',['Excellent','Good','Fair','Poor']), o('naturalLighting','Natural Lighting',['Excellent','Good','Fair','Poor']), o('privacyLevel','Privacy Level',['High','Moderate','Low']), o('wardrobeStorage','Wardrobe / Storage',['Built-in Wardrobe','Freestanding Wardrobe','Storage Space Only','None'],false),
  ]),
  [PropertyType.DUPLEX]: base([
    o('duplexType','Duplex Type',['Detached Duplex','Semi-Detached Duplex','Terrace Duplex']), o('numberOfFloors','Number of Floors',['2 Floors','3 Floors','4+ Floors']), o('ensuiteArrangement','Ensuite Arrangement',['All Bedrooms En-suite','Some Bedrooms En-suite','Master Bedroom Only En-suite','No Bedroom En-suite']), o('numberOfLivingAreas','Number of Living Areas',['1','2','3+']), o('kitchenArrangement','Kitchen Arrangement',['Standard Private Kitchen','Open-Plan Kitchen','Kitchen + Pantry','Kitchen + Store','Other']), o('parkingCapacity','Parking Capacity',['1 Car','2 Cars','3 Cars','4+ Cars','No Dedicated Parking']), o('compoundArrangement','Compound Arrangement',['Private Compound','Shared Compound','Estate / Common Compound']), o('outdoorSpace','Outdoor Space',['Private Yard / Garden','Small Private Outdoor Space','Shared Outdoor Space','No Dedicated Outdoor Space']), o('electricityMetering','Electricity Metering',['Prepaid Meter','Postpaid Meter','Shared Meter','Electricity Included in Rent','No Dedicated Meter']), o('waterStorage','Water Storage / Backup',['Overhead Tank','Ground Tank','Both','No Dedicated Storage','Not Sure']), o('ventilation','Ventilation',['Excellent','Good','Fair','Poor']), o('naturalLighting','Natural Lighting',['Excellent','Good','Fair','Poor']), o('privacyLevel','Privacy Level',['High','Moderate','Low']),
  ]),
  [PropertyType.BUNGALOW]: base([
    o('bungalowType','Bungalow Type',['Detached Bungalow','Semi-Detached Bungalow','Terrace Bungalow']), o('ensuiteArrangement','Ensuite Arrangement',['All Bedrooms En-suite','Some Bedrooms En-suite','Master Bedroom Only En-suite','No Bedroom En-suite']), o('electricityMetering','Electricity Metering',['Prepaid Meter','Postpaid Meter','Shared Meter','Electricity Included in Rent','No Dedicated Meter']), o('parkingCapacity','Parking Capacity',['1 Car','2 Cars','3 Cars','4+ Cars','No Dedicated Parking']), o('compoundArrangement','Compound Arrangement',['Private Compound','Shared Compound','Estate / Common Compound']), o('outdoorSpace','Outdoor Space',['Private Yard / Garden','Small Private Outdoor Space','Shared Outdoor Space','No Dedicated Outdoor Space']), o('waterStorage','Water Storage / Backup',['Overhead Tank','Ground Tank','Both','No Dedicated Storage','Not Sure']), o('ventilation','Ventilation',['Excellent','Good','Fair','Poor']), o('naturalLighting','Natural Lighting',['Excellent','Good','Fair','Poor']), o('privacyLevel','Privacy Level',['High','Moderate','Low']),
  ]),
  [PropertyType.SHARED_APARTMENT]: base([
    n('totalBedrooms','Total Bedrooms in Apartment'), o('maximumOccupants','Maximum Occupants in Available Room',['1','2','3','4+']), o('genderEligibility','Gender Eligibility',['Male Only','Female Only','Any Gender']), n('currentOccupants','Current Occupants'), n('totalIntendedOccupants','Total Intended Occupants'), o('existingOccupantArrangement','Existing Occupant Arrangement',['Male Only','Female Only','Mixed Gender','Currently Vacant']), o('bathroomArrangement','Bathroom Arrangement',['Private Bathroom','Shared with 1 Person','Shared with 2 People','Shared with 3+ People']), o('kitchenArrangement','Kitchen Arrangement',['Shared Kitchen','Private Kitchen / Kitchenette','No Kitchen Access']), o('livingRoomAccess','Living Room Access',['Full Access','Limited Access','No Access']), o('electricityPayment','Electricity Payment',['Shared Equally','Based on Usage','Fixed Contribution','Included in Rent','Other Arrangement']), o('cleaningArrangement','Cleaning Arrangement',['Occupants Clean Individually','Shared Cleaning Rotation','Paid Cleaner','Landlord / Management Provides Cleaning','No Fixed Arrangement']), o('privacyLevel','Privacy Level',['High','Moderate','Low']), o('noiseWithinApartment','Noise Within Apartment',['Quiet','Moderate','Often Noisy']), o('visitorPolicy','Visitors Policy',['Visitors Freely Allowed','Visitors Allowed With Restrictions','Daytime Visitors Only','No Visitors Allowed']), o('overnightGuests','Overnight Guests',['Allowed','Allowed With Restrictions','Not Allowed']), o('sharedApartmentRules','Shared Apartment Rules',[],false),
  ]),
  [PropertyType.HOSTEL]: base([
    o('accommodationType','Hostel Accommodation Type',['Purpose-Built Hostel','Converted Residential Property','Lodge','Shared Hostel Apartment','Other']), o('suitableFor','Suitable For',['Students','NYSC Members','Working Professionals','Temporary Residents'],false), o('genderRestriction','Gender Restriction',['Male Only','Female Only','Mixed','No Restriction']), o('occupancyArrangement','Occupancy Arrangement',['Single Occupancy','2 Persons per Room','3 Persons per Room','4 Persons per Room','5+ Persons per Room']), o('bathroomArrangement','Bathroom Arrangement',['Private / En-suite','Shared Within Room/Unit','Communal / Shared Outside Room']), o('kitchenArrangement','Kitchen Arrangement',['Private Kitchen','Shared Kitchen','Communal Cooking Area','No Kitchen']), o('cookingAllowed','Cooking Allowed?',['Yes','Designated Area Only','No']), o('roomFurnishing','Room Furnishing',['Fully Furnished','Partially Furnished','Unfurnished']), o('nearestInstitution','Nearest Institution',[],false), o('distanceFromInstitution','Distance from Institution',[],false), o('privacyLevel','Privacy Level',['High','Moderate','Low']), o('cleanliness','Cleanliness',['Excellent','Good','Fair','Poor']), o('noiseWithinHostel','Noise Within Hostel',['Very Quiet','Quiet','Moderate','Noisy','Very Noisy']), o('curfew','Curfew',['No Curfew','Curfew Applies']), o('curfewTime','Curfew Time',[],false), o('rentPeriod','Rent Period',['Monthly','Per Semester','Per Academic Session','Annually']),
  ]),
  [PropertyType.SHORT_STAY]: base([
    o('shortStayType','Short Stay Type',['Entire Apartment','Serviced Apartment','Studio Apartment','Private Room','Hotel/Guest House Room']), n('beds','Beds'), n('maximumGuests','Maximum Guests'), o('pricingModel','Pricing Model',['Daily','Weekly','Daily & Weekly']), n('dailyRate','Daily Rate (N/night)',false), n('weeklyRate','Weekly Rate (N/week)',false), n('minimumNights','Minimum Nights',false), n('maximumNights','Maximum Nights',false), o('checkInTime','Check-in Time',[],false), o('checkOutTime','Check-out Time',[],false), o('acCoverage','AC Coverage',['All Rooms','Bedrooms Only','Living Area Only','Partial Coverage','No Air Conditioning']), o('wifiReliability','Wi-Fi Reliability',['Very Reliable','Reliable','Fair','Unreliable','No Wi-Fi']), o('cleanliness','Cleanliness',['Excellent','Good','Fair','Poor']), o('furnishingLevel','Furnishing Level',['Fully Furnished','Mostly Furnished','Partially Furnished','Minimally Furnished']), o('kitchenAccess','Kitchen Access',['Private Full Kitchen','Private Kitchenette','Shared Kitchen','Limited Cooking Facility','No Kitchen Access']), o('powerBackupReliability','Power Backup Reliability',['Very Reliable','Reliable','Occasional','Unreliable','No Backup Power']), o('feesIncluded','All Mandatory Fees Included?',['Yes','No']), n('cleaningFee','Cleaning Fee',false), n('securityDeposit','Caution / Security Deposit',false), n('otherMandatoryFee','Other Mandatory Fee',false), o('otherMandatoryFeeDescription','Other Mandatory Fee Description',[],false),
  ]),
};
