import { MediaSection, PropertyType } from '@/types';

export type ListingField = { key: string; label: string; type?: 'number'|'text'|'textarea'|'time'|'checkbox'|'multi'; options?: string[]; required?: boolean; maxLength?: number; showWhen?: { key: string; values: Array<string|number|boolean> } };
export type MediaRequirement = { section: MediaSection; label: string; hint: string; minimum: number };
const s=(key:string,label:string,options:string[],required=true):ListingField=>({key,label,options,required});
const n=(key:string,label:string,required=true):ListingField=>({key,label,type:'number',required});
const t=(key:string,label:string,maxLength?:number):ListingField=>({key,label,type:maxLength?'textarea':'text',maxLength});
const metering=s('electricityMetering','Electricity Metering',['Prepaid Meter','Postpaid Meter','Shared Meter','Electricity Included in Rent','No Dedicated Meter']);
const parking=s('parkingAvailability','Parking Availability',['Available','Limited','Not Available']);
const storage=s('waterStorage','Water Storage / Backup',['Overhead Tank','Ground Tank','Both','No Dedicated Storage','Not Sure']);
const ensuite=s('ensuiteArrangement','Ensuite Arrangement',['All Bedrooms En-suite','Some Bedrooms En-suite','Master Bedroom Only En-suite','No Bedroom En-suite']);
const capacity=s('parkingCapacity','Parking Capacity',['1 Car','2 Cars','3 Cars','4+ Cars','No Dedicated Parking']);
const compound=s('compoundArrangement','Compound Arrangement',['Private Compound','Shared Compound','Estate / Common Compound']);

export const LISTING_FIELDS:Record<string,ListingField[]>={
 [PropertyType.SELF_CONTAIN]:[metering,parking,storage],
 [PropertyType.ROOM_AND_PARLOUR]:[metering,parking,storage],
 [PropertyType.MINI_FLAT]:[metering,parking,storage],
 [PropertyType.FLAT]:[ensuite,metering,parking,storage],
 [PropertyType.DUPLEX]:[s('numberOfFloors','Number of Floors',['2 Floors','3 Floors','4+ Floors']),s('duplexType','Duplex Type',['Detached','Semi-Detached','Terrace']),ensuite,metering,capacity,compound,storage],
 [PropertyType.BUNGALOW]:[s('bungalowType','Bungalow Type',['Detached','Semi-Detached','Terrace']),ensuite,metering,capacity,compound,storage],
 [PropertyType.SHARED_APARTMENT]:[
  n('totalBedrooms','Total Bedrooms in Apartment'),s('maximumOccupants','Maximum Occupants in Available Room',['1','2','3','4+']),s('genderEligibility','Gender Eligibility',['Male Only','Female Only','Any Gender']),n('currentOccupants','Current Occupants'),n('totalIntendedOccupants','Total Intended Occupants'),s('existingOccupantArrangement','Existing Occupant Arrangement',['Male Only','Female Only','Mixed Gender','Currently Vacant']),s('bathroomArrangement','Bathroom Arrangement',['Private Bathroom','Shared with 1 Person','Shared with 2 People','Shared with 3+ People']),s('electricityPayment','Electricity Payment',['Shared Equally','Based on Usage','Fixed Contribution','Included in Rent','Other Arrangement']),s('visitorPolicy','Visitors Policy',['Visitors Freely Allowed','Visitors Allowed With Restrictions','Daytime Visitors Only','No Visitors Allowed']),s('overnightGuests','Overnight Guests',['Allowed','Allowed With Restrictions','Not Allowed']),t('sharedApartmentRules','Shared Apartment Rules',300)
 ],
 [PropertyType.HOSTEL]:[
  s('accommodationType','Hostel Accommodation Type',['Purpose-Built Hostel','Converted Residential Property','Lodge','Shared Hostel Apartment','Other']),{key:'suitableFor',label:'Suitable For',type:'multi',options:['Students','NYSC Members','Working Professionals','Temporary Residents']},s('genderRestriction','Gender Restriction',['Male Only','Female Only','Mixed','No Restriction']),s('occupancyArrangement','Occupancy Arrangement',['Single Occupancy','2 Persons per Room','3 Persons per Room','4 Persons per Room','5+ Persons per Room']),s('bathroomArrangement','Bathroom Arrangement',['Private / En-suite','Shared Within Room/Unit','Communal / Shared Outside Room']),s('cookingAllowed','Cooking Allowed',['Yes','Designated Area Only','No']),s('roomFurnishing','Room Furnishing',['Fully Furnished','Partially Furnished','Unfurnished']),t('nearestInstitution','Nearest Institution'),t('distanceFromInstitution','Distance from Institution'),{key:'mealsIncluded',label:'Meals Included',type:'checkbox'},t('houseRules','House Rules',500),s('privacyLevel','Privacy Level',['High','Moderate','Low']),s('cleanliness','Cleanliness',['Excellent','Good','Fair','Poor']),s('noiseWithinHostel','Noise Within Hostel',['Very Quiet','Quiet','Moderate','Noisy','Very Noisy']),s('curfew','Curfew',['No Curfew','Curfew Applies']),{key:'curfewTime',label:'Curfew Time',type:'time',required:true,showWhen:{key:'curfew',values:['Curfew Applies']}},s('rentPeriod','Rent Period',['Monthly','Per Semester','Per Academic Session','Annually']),n('otherMandatoryFee','Other Mandatory Fee',false),{...t('otherMandatoryFeeDescription','Fee Description'),showWhen:{key:'otherMandatoryFee',values:[1]}}
 ],
 [PropertyType.SHORT_STAY]:[
  s('shortLetType','Short Let Type',['Studio Apartment','Serviced Apartment','Duplex / House','Private Room']),n('beds','Beds'),n('maximumGuests','Maximum Guests'),s('pricingModel','Pricing Model',['Daily','Weekly','Daily & Weekly']),{...n('dailyRate','Daily Rate (N/night)'),showWhen:{key:'pricingModel',values:['Daily','Daily & Weekly']}},{...n('weeklyRate','Weekly Rate (N/week)'),showWhen:{key:'pricingModel',values:['Weekly','Daily & Weekly']}},n('monthlyRate','Monthly Rate',false),n('minimumNights','Minimum Nights',false),{key:'checkInTime',label:'Check-in Time',type:'time'},{key:'checkOutTime',label:'Check-out Time',type:'time'},{key:'amenities',label:'Amenities',type:'multi',options:['Wi-Fi','Air Conditioning','Generator / Power Backup','Kitchen','Hot Water','Parking','Security / Gate','Laundry','Smart TV','Swimming Pool','Refrigerator','Microwave','Balcony','Gym']},t('houseRules','House Rules',500),s('wifiReliability','Wi-Fi Reliability',['Very Reliable','Reliable','Fair','Unreliable','No Wi-Fi']),s('powerBackupReliability','Power Backup Reliability',['Very Reliable','Reliable','Occasional','Unreliable','No Backup Power']),s('waterReliability','Water Reliability',['Always Available','Mostly Available','Occasional Interruptions','Unreliable']),s('acCoverage','AC Coverage',['All Rooms','Bedrooms Only','Living Area Only','Partial Coverage','No Air Conditioning']),s('cleanliness','Cleanliness',['Excellent','Good','Fair','Poor']),s('feesIncluded','All Mandatory Fees Included?',['Yes','No']),n('cleaningFee','Cleaning Fee',false),n('securityDeposit','Caution / Security Deposit',false),n('otherMandatoryFee','Other Mandatory Fee',false),{...t('otherMandatoryFeeDescription','Fee Description'),showWhen:{key:'otherMandatoryFee',values:[1]}}
 ]
};

const m=(section:MediaSection,label:string,hint:string):MediaRequirement=>({section,label,hint,minimum:1});
const road=m(MediaSection.ROAD_ACCESS,'Road Access','Road leading to the property');
const env=m(MediaSection.ENVIRONMENT,'Surroundings','Immediate surroundings');
const bath=m(MediaSection.BATHROOM,'Bathroom / Toilet','Bathroom and toilet facilities');
const ext=m(MediaSection.COMPOUND,'Compound / Exterior','Compound and exterior');
export const MEDIA_REQUIREMENTS:Record<string,MediaRequirement[]>={
 [PropertyType.SELF_CONTAIN]:[road,env,m(MediaSection.MAIN_ROOM,'Main Room','Living and sleeping space'),m(MediaSection.KITCHEN,'Kitchen','Private kitchen'),bath,ext],
 [PropertyType.ROOM_AND_PARLOUR]:[road,env,m(MediaSection.BEDROOM,'Room / Bedroom','Main room'),m(MediaSection.LIVING_ROOM,'Parlour / Living Room','Separate parlour'),m(MediaSection.KITCHEN,'Kitchen','Dedicated kitchen'),bath,ext],
 [PropertyType.MINI_FLAT]:[road,env,m(MediaSection.BEDROOM,'Bedroom','Bedroom'),m(MediaSection.LIVING_ROOM,'Living Room / Parlour','Living room'),m(MediaSection.KITCHEN,'Kitchen','Private kitchen'),bath,ext],
 [PropertyType.FLAT]:[road,env,m(MediaSection.LIVING_ROOM,'Living Room','Living room'),m(MediaSection.KITCHEN,'Kitchen','Kitchen'),m(MediaSection.BEDROOM,'Bedroom(s)','Representative bedrooms'),bath,ext],
 [PropertyType.DUPLEX]:[road,env,m(MediaSection.EXTERIOR,'Exterior / Building','Building exterior'),m(MediaSection.LIVING_ROOM,'Living Room(s)','Living areas'),m(MediaSection.KITCHEN,'Kitchen','Kitchen'),m(MediaSection.BEDROOM,'Bedroom(s)','Representative bedrooms'),bath,m(MediaSection.COMPOUND,'Compound / Parking','Compound and parking')],
 [PropertyType.BUNGALOW]:[road,env,m(MediaSection.EXTERIOR,'Exterior / Building','Building exterior'),m(MediaSection.LIVING_ROOM,'Living Room','Living room'),m(MediaSection.KITCHEN,'Kitchen','Kitchen'),m(MediaSection.BEDROOM,'Bedroom(s)','Representative bedrooms'),bath,m(MediaSection.COMPOUND,'Compound / Parking','Compound and parking')],
 [PropertyType.SHARED_APARTMENT]:[road,env,m(MediaSection.BEDROOM,'Available Bedroom','Exact room being offered'),bath,{...m(MediaSection.KITCHEN,'Kitchen / Shared Kitchen','Upload only when occupants have access'),minimum:0},{...m(MediaSection.LIVING_ROOM,'Living Room / Shared Area','Upload only when occupants have access'),minimum:0},ext],
 [PropertyType.HOSTEL]:[road,env,m(MediaSection.BEDROOM,'Room / Bedroom','Hostel room'),bath,ext,m(MediaSection.KITCHEN,'Kitchen / Cooking Area','Cooking facility'),{...m(MediaSection.COMMON_AREA,'Common Area','Upload only where a common area exists'),minimum:0}],
 [PropertyType.SHORT_STAY]:[road,env,m(MediaSection.EXTERIOR,'Exterior / Building','Property exterior'),m(MediaSection.BEDROOM,'Bedroom(s)','Guest bedroom'),m(MediaSection.MAIN_ROOM,'Main Accommodation / Sleeping Area','Studio sleeping area'),bath,m(MediaSection.KITCHEN,'Kitchen','Guest kitchen'),m(MediaSection.LIVING_ROOM,'Living Room','Separate living room'),{...ext,label:'Compound / Parking',minimum:0},{...m(MediaSection.COMMON_AREA,'Special Amenities','Pool, gym, balcony or another notable facility'),minimum:0}]
};
export const MEDIA_OVERALL_MINIMUM:Record<string,number>={
 [PropertyType.SELF_CONTAIN]:7,[PropertyType.ROOM_AND_PARLOUR]:7,[PropertyType.MINI_FLAT]:7,[PropertyType.FLAT]:8,[PropertyType.DUPLEX]:8,[PropertyType.BUNGALOW]:8,[PropertyType.SHARED_APARTMENT]:7,[PropertyType.HOSTEL]:7,[PropertyType.SHORT_STAY]:8
};
