import { PropertyType } from '@/types';

export type ListingField = { key: string; label: string; options?: string[]; type?: 'number' | 'text'; required?: boolean };
const o = (key: string, label: string, options: string[], required = true): ListingField => ({ key, label, options, required });
const n = (key: string, label: string, required = true): ListingField => ({ key, label, type: 'number', required });
const common = {
  meter: ['Private Prepaid', 'Private Postpaid', 'Shared Meter', 'Included in Service Charge', 'Not Confirmed'],
  parking: ['Dedicated', 'Shared Compound', 'Limited', 'Street Only', 'None', 'Not Confirmed'],
  storage: ['Private Tank', 'Shared Tank', 'No Dedicated Storage', 'Not Confirmed'],
  ventilation: ['Well', 'Moderate', 'Poor', 'Not Personally Verified'],
  lighting: ['Good', 'Moderate', 'Limited', 'Not Personally Verified'],
};
const base = (extra: ListingField[]): ListingField[] => extra;

export const LISTING_FIELDS: Record<string, ListingField[]> = {
  [PropertyType.FLAT]: base([
    o('bathroomArrangement','Bathroom Arrangement',['All Private','Some Shared','Outside Apartment','Not Confirmed']), o('kitchenType','Kitchen Type',['Private Kitchen','Kitchenette','Shared Kitchen','No Kitchen','Not Confirmed']), o('ensuiteArrangement','Ensuite Arrangement',['All Bedrooms','Some Bedrooms','None','Not Applicable','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingAvailability','Parking Availability',common.parking), o('waterStorage','Water Storage',common.storage), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Private Entrance/Facilities','Shared Entrance Only','Some Shared Facilities','Limited','Not Confirmed']), o('buildingOccupancy','Building Occupancy',['Few Units','Moderate','Dense','Newly Completed/Unoccupied','Not Confirmed'],false),
  ]),
  [PropertyType.MINI_FLAT]: base([
    o('bathroomArrangement','Bathroom Arrangement',['Private Inside Unit','Private Outside Unit','Shared','Not Confirmed']), o('kitchenArrangement','Kitchen Arrangement',['Private Kitchen','Kitchenette','Shared','No Kitchen','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingAvailability','Parking Availability',common.parking), o('waterStorage','Water Storage',common.storage), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Private Entrance/Facilities','Shared Entrance','Limited','Not Confirmed']),
  ]),
  [PropertyType.SELF_CONTAIN]: base([
    o('kitchenType','Kitchen Type',['Separate Private Kitchen','Private Kitchenette','Kitchen Space Within Room','No Kitchen','Not Confirmed']), o('bathroomLocation','Bathroom Location',['Inside Room','Attached but Externally Accessed','Outside and Private','Shared','Not Confirmed']), o('kitchenArrangement','Kitchen Arrangement',['Separate Private','Kitchenette','Within Room','No Kitchen','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingAvailability','Parking Availability',common.parking), o('waterStorage','Water Storage',common.storage), o('roomSize','Room Size',['Spacious','Moderate','Compact','Very Small','Not Personally Verified']), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Private Entrance/Facilities','Shared Entrance','Limited','Not Confirmed']),
  ]),
  [PropertyType.ROOM_AND_PARLOUR]: base([
    o('bathroomArrangement','Bathroom Arrangement',['Private Inside','Private Outside','Shared','Not Available','Not Confirmed']), o('toiletArrangement','Toilet Arrangement',['Private Inside','Private Outside','Shared','Not Confirmed']), o('kitchenArrangement','Kitchen Arrangement',['Private Inside','Private Outside','Shared','Designated Cooking Space','None','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingAvailability','Parking Availability',common.parking), o('waterStorage','Water Storage',common.storage), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Private Entrance','Shared Entrance','Shared Facilities','Limited','Not Confirmed']),
  ]),
  [PropertyType.DUPLEX]: base([
    o('duplexType','Duplex Type',['Detached','Semi-detached','Terrace','Duplex Apartment','Not Confirmed']), o('numberOfFloors','Number of Floors',['Two','Three','More Than Three','Not Confirmed']), o('ensuiteArrangement','Ensuite Arrangement',['All','Some','None','Not Confirmed']), n('numberOfLivingAreas','Number of Living Areas'), o('electricityMetering','Electricity Metering',common.meter), o('parkingCapacity','Parking Capacity',['1 Vehicle','2 Vehicles','3+','None','Not Confirmed']), o('compoundArrangement','Compound Arrangement',['Fully Private','Shared with Another Duplex','Shared Estate','Limited Space','Not Confirmed']), o('waterStorage','Water Storage',common.storage), o('staircaseCondition','Staircase Condition',['Good','Minor Issues','Steep/Difficult','Poor/Damaged','Not Personally Verified']), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Fully Private','Partly Shared','Limited','Not Confirmed']), o('premisesArrangement','Premises Arrangement',['Private Premises','Shared Premises','Estate Environment','Not Confirmed']),
  ]),
  [PropertyType.BUNGALOW]: base([
    o('bungalowType','Bungalow Type',['Detached','Semi-detached','Terrace','Within Shared Compound','Not Confirmed']), o('ensuiteArrangement','Ensuite Arrangement',['All','Some','None','Not Confirmed']), o('electricityMetering','Electricity Metering',common.meter), o('parkingCapacity','Parking Capacity',['1 Vehicle','2 Vehicles','3+','None','Not Confirmed']), o('compoundArrangement','Compound Arrangement',['Fully Private','Shared','Estate','Limited Space','None','Not Confirmed']), o('waterStorage','Water Storage',common.storage), o('roofCeilingCondition','Roof/Ceiling Condition',['Good','Minor Issues','Leakage/Damp Signs','Visible Damage','Not Personally Verified']), o('ventilation','Ventilation',common.ventilation), o('naturalLighting','Natural Lighting',common.lighting), o('privacyLevel','Privacy Level',['Fully Private','Partly Shared','Limited','Not Confirmed']), o('premisesArrangement','Premises Arrangement',['Private Premises','Shared Compound','Estate Environment','Not Confirmed']),
  ]),
  [PropertyType.SHARED_APARTMENT]: base([
    o('bedroomType','Bedroom Type',['Private Ensuite','Private with Shared Bathroom','Shared Bedroom','Master Bedroom','Not Confirmed']), n('totalBedrooms','Total Bedrooms in Apartment'), n('maximumOccupants','Maximum Occupants for Available Room'), o('genderEligibility','Gender Eligibility',['Male Only','Female Only','Open to Any Gender','Not Confirmed']), n('currentOccupants','Current Occupants'), n('totalIntendedOccupants','Total Intended Occupants'), o('existingOccupantArrangement','Existing Occupant Arrangement',['All Male','All Female','Mixed','No Current Occupants','Not Confirmed']), o('bathroomArrangement','Bathroom Arrangement',['Private Ensuite','Dedicated Outside Room','Shared with One','Shared with Multiple','Not Confirmed']), o('kitchenArrangement','Kitchen Arrangement',['Shared Full Access','Shared Restricted','Kitchenette','Cooking Not Allowed','Not Confirmed']), o('livingRoomAccess','Living Room Access',['Full','Limited','None','Not Confirmed']), o('electricityPayment','Electricity Payment',['Included in Rent','Service Charge','Shared Equally','Usage-based','Separate Meter','Not Confirmed']), o('cleaningArrangement','Cleaning Arrangement',['Occupants Clean','Rota','Cleaner Provided','Paid Cleaner Shared','None','Not Confirmed']), o('visitorPolicy','Visitor Policy',['Allowed','Specified Hours','Same-gender Only','No Overnight','Not Allowed','Not Confirmed']), o('privacyLevel','Privacy Level',['Private Lockable Room','Private Without Lock','Shared Sleeping Space','Limited','Not Confirmed']), o('noiseWithinApartment','Noise Within Apartment',['Quiet','Moderate','Frequent','Varies','Not Confirmed']),
  ]),
  [PropertyType.HOSTEL]: base([
    o('accommodationType','Hostel Accommodation Type',['Self-contained Room','Single Room','Shared Room','Bedspace']), o('rentPeriod','Rent Period',['Per Academic Session','Per Year','Per Semester']), o('occupancyArrangement','Occupancy Arrangement',['Private','Shared by 2','3','4','More Than 4','Not Confirmed']), o('bathroomArrangement','Bathroom Arrangement',['Private','Shared Within Room','Shared by Multiple Rooms','General Bathroom','Not Confirmed']), o('kitchenArrangement','Kitchen Arrangement',['Private','Shared','Designated Cooking Area','Cooking Not Allowed','Not Confirmed']), o('roomFurnishing','Room Furnishing',['Fully','Partly','Minimal','Unfurnished','Not Confirmed']), o('privacyLevel','Privacy Level',['Private','Shared with Limited Privacy','Open/shared','Not Confirmed']), o('cleanliness','Cleanliness',['Very Clean','Clean/Minor Issues','Requires Cleaning','Poor','Not Personally Verified']), o('noiseWithinHostel','Noise Within Hostel',['Quiet','Moderate','Frequent','Varies','Not Confirmed']), o('curfew','Curfew',['No Curfew','Applies','Varies','Not Confirmed']), o('cookingAllowed','Cooking Allowed',['Inside Room','Designated Kitchen','Restricted','Not Allowed','Not Confirmed']), o('nearbyInstitution','Nearby Institution',[],true),
  ]),
  [PropertyType.SHORT_STAY]: base([
    o('shortStayType','Short Stay Type',['Entire Apartment','Serviced Apartment','Studio','Private Room','Hotel Room','Guest House','Duplex']), n('beds','Beds'), n('maximumGuests','Maximum Guests'), o('acCoverage','AC Coverage',['All Bedrooms/Living Room','Bedrooms Only','Some Rooms','None','Not Confirmed']), o('wifiReliability','Wi-Fi Reliability',['Reliable','Sometimes Unstable','Limited Data','None','Not Confirmed']), o('cleanliness','Cleanliness',['Very Clean','Clean/Minor Issues','Requires Cleaning','Poor','Not Personally Verified']), o('furnishingLevel','Furnishing Level',['Fully Equipped','Fully/Basic','Partly','Minimal','Not Personally Verified']), o('kitchenAvailability','Kitchen Availability',['Private Full','Private Basic','Shared','Kitchenette','None','Not Confirmed']), o('powerBackupReliability','Power Backup Reliability',['24-hour','During Outages','Limited Appliances','None','Not Confirmed']), o('feesIncluded','All Mandatory Fees Included?',['Yes','No']),
  ]),
};
